//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=NextWay;Persist Security Info=True;User ID=sa;Passw" +
            "ord=admin@123;MultipleActiveResultSets=True;Application Name=EntityFramework")]
        public string NextWayConnectionString {
            get {
                return ((string)(this["NextWayConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=NextWay;Persist Security Info=True;User ID=sa;Passw" +
            "ord=admin@123")]
        public string NextWayConnectionString1 {
            get {
                return ((string)(this["NextWayConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=NextWay;Integrated Security=True")]
        public string NextWayConnectionString2 {
            get {
                return ((string)(this["NextWayConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=.;initial catalog=avSVAW;persist security info=True;user id=sa;passwo" +
            "rd=159753;MultipleActiveResultSets=True;Application Name=EntityFramework")]
        public string SVAWConStr {
            get {
                return ((string)(this["SVAWConStr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=data source=.;initial catalog=avSVAW;persist security info=True;user " +
            "id=sa;password=159753")]
        public string SVAWConStr1 {
            get {
                return ((string)(this["SVAWConStr1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=data source=.;initial catalog=avSVAW;persist security info=True;Integ" +
            "rated Security=True")]
        public string SVAWConStr2 {
            get {
                return ((string)(this["SVAWConStr2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SVAW_BK;Persist Security Info=True;User ID=sa;Passw" +
            "ord=159753;MultipleActiveResultSets=True;Application Name=EntityFramework")]
        public string SVAW_BKConnectionString {
            get {
                return ((string)(this["SVAW_BKConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=avSVAW;Persist Security Info=True;User ID=sa;Passwo" +
            "rd=123456;MultipleActiveResultSets=True;Application Name=EntityFramework")]
        public string avSVAWConnectionString1 {
            get {
                return ((string)(this["avSVAWConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=avAndonAriston;Persist Security Info=True;User ID=s" +
            "a;Password=123;MultipleActiveResultSets=True;Application Name=EntityFramework")]
        public string avSVAWConnectionString {
            get {
                return ((string)(this["avSVAWConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=avAndonAriston;Persist Security Info=Tru" +
            "e;User ID=sa;MultipleActiveResultSets=True;Application Name=EntityFramework")]
        public string avAndonAristonConnectionString {
            get {
                return ((string)(this["avAndonAristonConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;Initial Catalog=avAndonAriston;Persist Security Info=Tru" +
            "e;User ID=sa;Password=123;MultipleActiveResultSets=True;Application Name=EntityF" +
            "ramework")]
        public string avAndonAristonConnectionString1 {
            get {
                return ((string)(this["avAndonAristonConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-E9CFLMM\\SQLEXPRESS;Initial Catalog=avAndon;Persist Security I" +
            "nfo=True;User ID=sa;Password=123;MultipleActiveResultSets=True;Application Name=" +
            "EntityFramework")]
        public string avAndonConnectionString {
            get {
                return ((string)(this["avAndonConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-E9CFLMM\\SQLEXPRESS;Initial Catalog=Avani.Andon;Persist Securi" +
            "ty Info=True;User ID=sa;Password=123;MultipleActiveResultSets=True;Application N" +
            "ame=EntityFramework")]
        public string Avani_AndonConnectionString {
            get {
                return ((string)(this["Avani_AndonConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQL_EN;Initial Catalog=Avani.Andon;Persist Security Info=True;User " +
            "ID=sa;Password=admin@123;MultipleActiveResultSets=True;Application Name=EntityFr" +
            "amework")]
        public string Avani_AndonConnectionString1 {
            get {
                return ((string)(this["Avani_AndonConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.254;Initial Catalog=Avani.Andon;Persist Security Info=True;" +
            "User ID=sa;Password=admin@123;MultipleActiveResultSets=True;Application Name=Ent" +
            "ityFramework")]
        public string Avani_AndonConnectionString2 {
            get {
                return ((string)(this["Avani_AndonConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-T363Q3B\\SQLEXPRESS;Initial Catalog=Avani.Andon;Persist Securi" +
            "ty Info=True;User ID=sa;MultipleActiveResultSets=True;Application Name=EntityFra" +
            "mework")]
        public string Avani_AndonConnectionString3 {
            get {
                return ((string)(this["Avani_AndonConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-G3LMUCK\\SQLEXPRESS;Initial Catalog=Avani.Andon;Persist Securi" +
            "ty Info=True;User ID=sa;Password=123;MultipleActiveResultSets=True;Application N" +
            "ame=EntityFramework")]
        public string Avani_AndonConnectionString4 {
            get {
                return ((string)(this["Avani_AndonConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ADMIN-PC\\SQLEXPRESS;Initial Catalog=Avani.Andon;Persist Security Info" +
            "=True;User ID=sa;Password=123;MultipleActiveResultSets=True;Application Name=Ent" +
            "ityFramework")]
        public string Avani_AndonConnectionString5 {
            get {
                return ((string)(this["Avani_AndonConnectionString5"]));
            }
        }
        
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-H4N9TFU\\SQLEXPRESS;Initial Catalog=Andon.MES.KGR;Integrated S" +
            "ecurity=True")]
        public string Andon_MES_KGRConnectionString {
            get {
                return ((string)(this["Andon_MES_KGRConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-UT3VJ3N\\SQLEXPRESS;Initial Catalog=Avani.Andon;Persist Securi" +
            "ty Info=True;User ID=sa;Password=123;MultipleActiveResultSets=True;Application N" +
            "ame=EntityFramework")]
        public string Avani_AndonConnectionString7 {
            get {
                return ((string)(this["Avani_AndonConnectionString7"]));
            }
        }
    }
}
