//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Language", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        internal static string Actual {
            get {
                return ResourceManager.GetString("Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine&apos;s position will blink when stopped over allowed stop duration!.
        /// </summary>
        internal static string AlertMonitor {
            get {
                return ResourceManager.GetString("AlertMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andon Call.
        /// </summary>
        internal static string AndonCall {
            get {
                return ResourceManager.GetString("AndonCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for.
        /// </summary>
        internal static string ApplyTo {
            get {
                return ResourceManager.GetString("ApplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Generate.
        /// </summary>
        internal static string AutoGenerate {
            get {
                return ResourceManager.GetString("AutoGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BreakTime.
        /// </summary>
        internal static string BreakTime {
            get {
                return ResourceManager.GetString("BreakTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Event.
        /// </summary>
        internal static string ByEvent {
            get {
                return ResourceManager.GetString("ByEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Line.
        /// </summary>
        internal static string ByLine {
            get {
                return ResourceManager.GetString("ByLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Month.
        /// </summary>
        internal static string ByMonth {
            get {
                return ResourceManager.GetString("ByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Machine.
        /// </summary>
        internal static string ByNode {
            get {
                return ResourceManager.GetString("ByNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Quarter.
        /// </summary>
        internal static string ByQuar {
            get {
                return ResourceManager.GetString("ByQuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Week.
        /// </summary>
        internal static string ByWeek {
            get {
                return ResourceManager.GetString("ByWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Year.
        /// </summary>
        internal static string ByYear {
            get {
                return ResourceManager.GetString("ByYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Zone.
        /// </summary>
        internal static string ByZone {
            get {
                return ResourceManager.GetString("ByZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Help.
        /// </summary>
        internal static string CallHelp {
            get {
                return ResourceManager.GetString("CallHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Logs.
        /// </summary>
        internal static string CallLogs {
            get {
                return ResourceManager.GetString("CallLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Logs List.
        /// </summary>
        internal static string CallLogsList {
            get {
                return ResourceManager.GetString("CallLogsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call On.
        /// </summary>
        internal static string CallOn {
            get {
                return ResourceManager.GetString("CallOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        internal static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar chart.
        /// </summary>
        internal static string ChartBar {
            get {
                return ResourceManager.GetString("ChartBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie chart.
        /// </summary>
        internal static string ChartPie {
            get {
                return ResourceManager.GetString("ChartPie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart style.
        /// </summary>
        internal static string ChartType {
            get {
                return ResourceManager.GetString("ChartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classify.
        /// </summary>
        internal static string Classify {
            get {
                return ResourceManager.GetString("Classify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        internal static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config Service.
        /// </summary>
        internal static string ConfigService {
            get {
                return ResourceManager.GetString("ConfigService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has this plan stopped?.
        /// </summary>
        internal static string ConfirmStoped {
            get {
                return ResourceManager.GetString("ConfirmStoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase continuously on each line.
        /// </summary>
        internal static string ContinueIncreaseLine {
            get {
                return ResourceManager.GetString("ContinueIncreaseLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        internal static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DayOfWeek.
        /// </summary>
        internal static string DayOfWeek {
            get {
                return ResourceManager.GetString("DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        internal static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you delete this information?.
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        internal static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down time.
        /// </summary>
        internal static string Downtime {
            get {
                return ResourceManager.GetString("Downtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownTime Report.
        /// </summary>
        internal static string DownTimeReport {
            get {
                return ResourceManager.GetString("DownTimeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        internal static string EffOperation {
            get {
                return ResourceManager.GetString("EffOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  English.
        /// </summary>
        internal static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Event.
        /// </summary>
        internal static string EventDef {
            get {
                return ResourceManager.GetString("EventDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events of the day.
        /// </summary>
        internal static string EventInDay {
            get {
                return ResourceManager.GetString("EventInDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Excel.
        /// </summary>
        internal static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        internal static string Factory {
            get {
                return ResourceManager.GetString("Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature list.
        /// </summary>
        internal static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinishHour.
        /// </summary>
        internal static string FinishHour {
            get {
                return ResourceManager.GetString("FinishHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinishTime.
        /// </summary>
        internal static string FinishTime {
            get {
                return ResourceManager.GetString("FinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder storage.
        /// </summary>
        internal static string FolderStorage {
            get {
                return ResourceManager.GetString("FolderStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Fr {
            get {
                return ResourceManager.GetString("Fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Company Name.
        /// </summary>
        internal static string FullCompanyName {
            get {
                return ResourceManager.GetString("FullCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen.
        /// </summary>
        internal static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headcount.
        /// </summary>
        internal static string Headcount {
            get {
                return ResourceManager.GetString("Headcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportProduction.
        /// </summary>
        internal static string ImportProduction {
            get {
                return ResourceManager.GetString("ImportProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 days.
        /// </summary>
        internal static string In7days {
            get {
                return ResourceManager.GetString("In7days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        internal static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        internal static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        internal static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language1 {
            get {
                return ResourceManager.GetString("Language1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leader.
        /// </summary>
        internal static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineCode.
        /// </summary>
        internal static string LineCode {
            get {
                return ResourceManager.GetString("LineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineName.
        /// </summary>
        internal static string LineName {
            get {
                return ResourceManager.GetString("LineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineSchedule.
        /// </summary>
        internal static string LineSchedule {
            get {
                return ResourceManager.GetString("LineSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Loss.
        /// </summary>
        internal static string ListLoss {
            get {
                return ResourceManager.GetString("ListLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance status.
        /// </summary>
        internal static string ListStatus {
            get {
                return ResourceManager.GetString("ListStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Loginform {
            get {
                return ResourceManager.GetString("Loginform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loss.
        /// </summary>
        internal static string Loss {
            get {
                return ResourceManager.GetString("Loss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        internal static string Machine {
            get {
                return ResourceManager.GetString("Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max ProcessTime.
        /// </summary>
        internal static string MaxProcessTime {
            get {
                return ResourceManager.GetString("MaxProcessTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max StopTime.
        /// </summary>
        internal static string MaxStopTime {
            get {
                return ResourceManager.GetString("MaxStopTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max WaitTime.
        /// </summary>
        internal static string MaxWaitTime {
            get {
                return ResourceManager.GetString("MaxWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string MenuAddUser {
            get {
                return ResourceManager.GetString("MenuAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring Screen.
        /// </summary>
        internal static string MenuBigScreen {
            get {
                return ResourceManager.GetString("MenuBigScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string MenuCategory {
            get {
                return ResourceManager.GetString("MenuCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Configuration.
        /// </summary>
        internal static string MenuConfigSystem {
            get {
                return ResourceManager.GetString("MenuConfigSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MenuDictionary {
            get {
                return ResourceManager.GetString("MenuDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Configuration.
        /// </summary>
        internal static string MenuGeneralConfig {
            get {
                return ResourceManager.GetString("MenuGeneralConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string MenuGroup {
            get {
                return ResourceManager.GetString("MenuGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        internal static string MenuMonitoring {
            get {
                return ResourceManager.GetString("MenuMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machinery Monitoring.
        /// </summary>
        internal static string MenuMonitoringActivities {
            get {
                return ResourceManager.GetString("MenuMonitoringActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability Graph.
        /// </summary>
        internal static string MenuPerformanceGraph {
            get {
                return ResourceManager.GetString("MenuPerformanceGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Actual/Plan.
        /// </summary>
        internal static string MenuPlanAndPractice {
            get {
                return ResourceManager.GetString("MenuPlanAndPractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Configuration.
        /// </summary>
        internal static string MenuProduction {
            get {
                return ResourceManager.GetString("MenuProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string MenuReport {
            get {
                return ResourceManager.GetString("MenuReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running By Type.
        /// </summary>
        internal static string MenuReportByType {
            get {
                return ResourceManager.GetString("MenuReportByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Details.
        /// </summary>
        internal static string MenuReportDetails {
            get {
                return ResourceManager.GetString("MenuReportDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runing timeline.
        /// </summary>
        internal static string MenuRunningGraph {
            get {
                return ResourceManager.GetString("MenuRunningGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Plan.
        /// </summary>
        internal static string MenuRunPlan {
            get {
                return ResourceManager.GetString("MenuRunPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string MenuShift {
            get {
                return ResourceManager.GetString("MenuShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP Plan.
        /// </summary>
        internal static string MenuStopPlan {
            get {
                return ResourceManager.GetString("MenuStopPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration allowed.
        /// </summary>
        internal static string MenuTimeAllowed {
            get {
                return ResourceManager.GetString("MenuTimeAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string MenuUser {
            get {
                return ResourceManager.GetString("MenuUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Plan.
        /// </summary>
        internal static string MenuWorkingPlan {
            get {
                return ResourceManager.GetString("MenuWorkingPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        internal static string Method {
            get {
                return ResourceManager.GetString("Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Mo {
            get {
                return ResourceManager.GetString("Mo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production monitoring system.
        /// </summary>
        internal static string MonitoringProduction {
            get {
                return ResourceManager.GetString("MonitoringProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NG.
        /// </summary>
        internal static string NG {
            get {
                return ResourceManager.GetString("NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Name.
        /// </summary>
        internal static string Node {
            get {
                return ResourceManager.GetString("Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Type.
        /// </summary>
        internal static string NodeType {
            get {
                return ResourceManager.GetString("NodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Stop.
        /// </summary>
        internal static string NoofStop {
            get {
                return ResourceManager.GetString("NoofStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Machines.
        /// </summary>
        internal static string NumberOfNode {
            get {
                return ResourceManager.GetString("NumberOfNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Runs.
        /// </summary>
        internal static string NumberOfRunning {
            get {
                return ResourceManager.GetString("NumberOfRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Stops.
        /// </summary>
        internal static string NumberOfStop {
            get {
                return ResourceManager.GetString("NumberOfStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Machine Type.
        /// </summary>
        internal static string NumberOfType {
            get {
                return ResourceManager.GetString("NumberOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectType.
        /// </summary>
        internal static string ObjectType {
            get {
                return ResourceManager.GetString("ObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE.
        /// </summary>
        internal static string OEE {
            get {
                return ResourceManager.GetString("OEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operate.
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operational Report.
        /// </summary>
        internal static string OperationalReport {
            get {
                return ResourceManager.GetString("OperationalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Monitoring - F3.
        /// </summary>
        internal static string OperationMonitoring {
            get {
                return ResourceManager.GetString("OperationMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Timeline.
        /// </summary>
        internal static string OperationTimeline {
            get {
                return ResourceManager.GetString("OperationTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        internal static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan &amp; Actual.
        /// </summary>
        internal static string PlanAndPractice {
            get {
                return ResourceManager.GetString("PlanAndPractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanDuration.
        /// </summary>
        internal static string PlanDuration {
            get {
                return ResourceManager.GetString("PlanDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Finish.
        /// </summary>
        internal static string PlanFinish {
            get {
                return ResourceManager.GetString("PlanFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlannedQuantity.
        /// </summary>
        internal static string PlannedQuantity {
            get {
                return ResourceManager.GetString("PlannedQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Start.
        /// </summary>
        internal static string PlanStart {
            get {
                return ResourceManager.GetString("PlanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        internal static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice.
        /// </summary>
        internal static string Practice {
            get {
                return ResourceManager.GetString("Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        internal static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Duration.
        /// </summary>
        internal static string ProcessDuration {
            get {
                return ResourceManager.GetString("ProcessDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductCode.
        /// </summary>
        internal static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        internal static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductionCode.
        /// </summary>
        internal static string ProductionCode {
            get {
                return ResourceManager.GetString("ProductionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductionName.
        /// </summary>
        internal static string ProductionName {
            get {
                return ResourceManager.GetString("ProductionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Quality Report.
        /// </summary>
        internal static string ProductionQualityReport {
            get {
                return ResourceManager.GetString("ProductionQualityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production report.
        /// </summary>
        internal static string Productionreport {
            get {
                return ResourceManager.GetString("Productionreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production trend chart.
        /// </summary>
        internal static string Productiontrendchart {
            get {
                return ResourceManager.GetString("Productiontrendchart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productivity Report.
        /// </summary>
        internal static string ProductivityReport {
            get {
                return ResourceManager.GetString("ProductivityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        internal static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuantityPlanned.
        /// </summary>
        internal static string QuantityPlanned {
            get {
                return ResourceManager.GetString("QuantityPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuantityProduced.
        /// </summary>
        internal static string QuantityProduced {
            get {
                return ResourceManager.GetString("QuantityProduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Report.
        /// </summary>
        internal static string QuantityReport {
            get {
                return ResourceManager.GetString("QuantityReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemainQuantity.
        /// </summary>
        internal static string RemainQuantity {
            get {
                return ResourceManager.GetString("RemainQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report By.
        /// </summary>
        internal static string ReportBy {
            get {
                return ResourceManager.GetString("ReportBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Calender.
        /// </summary>
        internal static string ReportCalender {
            get {
                return ResourceManager.GetString("ReportCalender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportLine.
        /// </summary>
        internal static string ReportLine {
            get {
                return ResourceManager.GetString("ReportLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        internal static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequireWorkingPlan.
        /// </summary>
        internal static string RequireWorkingPlan {
            get {
                return ResourceManager.GetString("RequireWorkingPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequireYearAndMonth.
        /// </summary>
        internal static string RequireYearAndMonth {
            get {
                return ResourceManager.GetString("RequireYearAndMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResolvedDuration.
        /// </summary>
        internal static string ResolvedDuration {
            get {
                return ResourceManager.GetString("ResolvedDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Duration.
        /// </summary>
        internal static string RunningDuration {
            get {
                return ResourceManager.GetString("RunningDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Sa {
            get {
                return ResourceManager.GetString("Sa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScheduleCode.
        /// </summary>
        internal static string ScheduleCode {
            get {
                return ResourceManager.GetString("ScheduleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScheduleName.
        /// </summary>
        internal static string ScheduleName {
            get {
                return ResourceManager.GetString("ScheduleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Saver.
        /// </summary>
        internal static string ScreenSaver {
            get {
                return ResourceManager.GetString("ScreenSaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Av.
        /// </summary>
        internal static string ShortCompanyName {
            get {
                return ResourceManager.GetString("ShortCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowBar.
        /// </summary>
        internal static string ShowBar {
            get {
                return ResourceManager.GetString("ShowBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SS Code.
        /// </summary>
        internal static string SSCode {
            get {
                return ResourceManager.GetString("SSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartHour.
        /// </summary>
        internal static string StartHour {
            get {
                return ResourceManager.GetString("StartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start week.
        /// </summary>
        internal static string StartWeek {
            get {
                return ResourceManager.GetString("StartWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Status_Active {
            get {
                return ResourceManager.GetString("Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Status_Complete {
            get {
                return ResourceManager.GetString("Status_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Status_Completed {
            get {
                return ResourceManager.GetString("Status_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string Status_Delete {
            get {
                return ResourceManager.GetString("Status_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Active.
        /// </summary>
        internal static string Status_InActive {
            get {
                return ResourceManager.GetString("Status_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In production.
        /// </summary>
        internal static string Status_InProduction {
            get {
                return ResourceManager.GetString("Status_InProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has not yet started.
        /// </summary>
        internal static string Status_NoStart {
            get {
                return ResourceManager.GetString("Status_NoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Status_Pause {
            get {
                return ResourceManager.GetString("Status_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string Status_Plan {
            get {
                return ResourceManager.GetString("Status_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string Status_Run {
            get {
                return ResourceManager.GetString("Status_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Duration.
        /// </summary>
        internal static string StopDuration {
            get {
                return ResourceManager.GetString("StopDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stoped {
            get {
                return ResourceManager.GetString("Stoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Working Plan.
        /// </summary>
        internal static string StopWorkingPlan {
            get {
                return ResourceManager.GetString("StopWorkingPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Su {
            get {
                return ResourceManager.GetString("Su", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table style.
        /// </summary>
        internal static string TableType {
            get {
                return ResourceManager.GetString("TableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaktTime.
        /// </summary>
        internal static string TaktTime {
            get {
                return ResourceManager.GetString("TaktTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Th {
            get {
                return ResourceManager.GetString("Th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to scroll screen.
        /// </summary>
        internal static string Time2SwitchScreen {
            get {
                return ResourceManager.GetString("Time2SwitchScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time.
        /// </summary>
        internal static string TotalDuration {
            get {
                return ResourceManager.GetString("TotalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Availability.
        /// </summary>
        internal static string TotalPercent {
            get {
                return ResourceManager.GetString("TotalPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalQuantity.
        /// </summary>
        internal static string TotalQuantity {
            get {
                return ResourceManager.GetString("TotalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tu {
            get {
                return ResourceManager.GetString("Tu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Online Value.
        /// </summary>
        internal static string UpdateOnlineValue {
            get {
                return ResourceManager.GetString("UpdateOnlineValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string UserAdd {
            get {
                return ResourceManager.GetString("UserAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullName.
        /// </summary>
        internal static string UserFullName {
            get {
                return ResourceManager.GetString("UserFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using sound.
        /// </summary>
        internal static string UsingSound {
            get {
                return ResourceManager.GetString("UsingSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variation Chart.
        /// </summary>
        internal static string VariationChart {
            get {
                return ResourceManager.GetString("VariationChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Code.
        /// </summary>
        internal static string VendorCode {
            get {
                return ResourceManager.GetString("VendorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        internal static string VI {
            get {
                return ResourceManager.GetString("VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Report.
        /// </summary>
        internal static string ViewReport {
            get {
                return ResourceManager.GetString("ViewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait Duration.
        /// </summary>
        internal static string WaitDuration {
            get {
                return ResourceManager.GetString("WaitDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string We {
            get {
                return ResourceManager.GetString("We", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkingOrderPlan.
        /// </summary>
        internal static string WorkingOrderPlan {
            get {
                return ResourceManager.GetString("WorkingOrderPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Plan.
        /// </summary>
        internal static string WorkingPlan {
            get {
                return ResourceManager.GetString("WorkingPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Plan Detail.
        /// </summary>
        internal static string WorkingPlanDetail {
            get {
                return ResourceManager.GetString("WorkingPlanDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Shift.
        /// </summary>
        internal static string WorkingShift {
            get {
                return ResourceManager.GetString("WorkingShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkOrder.
        /// </summary>
        internal static string WorkOrder {
            get {
                return ResourceManager.GetString("WorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WS.
        /// </summary>
        internal static string WS {
            get {
                return ResourceManager.GetString("WS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        internal static string Zone {
            get {
                return ResourceManager.GetString("Zone", resourceCulture);
            }
        }
    }
}
